---
name: plugin-test

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: "tfsec --version"
