name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v3
        with:
          release-type: simple
