name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v3
        with:
          release-type: simple
